import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const toAbs = (p) => path.resolve(__dirname, p);

async function prerender() {
  const template = fs.readFileSync(toAbs('dist/index.html'), 'utf-8');
  
  // Import the SSR build
  // Note: This file is generated by `vite build --ssr`
  const { render } = await import('./dist-server/entry-server.js');
  
  console.log('Pre-rendering internal content...');
  const appHtml = render();
  
  const html = template.replace(`<!--app-html-->`, appHtml)
    .replace(`<div id="app"></div>`, `<div id="app">${appHtml}</div>`);

  fs.writeFileSync(toAbs('dist/index.html'), html);
  
  console.log('Build completed successfully with pre-rendered content for SEO and Accessibility.');
}

prerender();
